#!/usr/bin/env zsh

alien_theme(){
  [[ -z $ALIEN_PROMPT_FG ]] && ALIEN_PROMPT_FG=228

  [[ -z $ALIEN_SECTION_EXIT_FG ]] && ALIEN_SECTION_EXIT_FG=232
  [[ -z $ALIEN_SECTION_EXIT_BG ]] && ALIEN_SECTION_EXIT_BG=226
  [[ -z $ALIEN_SECTION_EXIT_BG_ERROR ]] && ALIEN_SECTION_EXIT_BG_ERROR=196

  [[ -z $ALIEN_SECTION_TIME_FG ]] && ALIEN_SECTION_TIME_FG=254
  [[ -z $ALIEN_SECTION_TIME_BG ]] && ALIEN_SECTION_TIME_BG=22

  [[ -z $ALIEN_SECTION_BATTERY_FG ]] && ALIEN_SECTION_BATTERY_FG=254
  [[ -z $ALIEN_SECTION_BATTERY_BG ]] && ALIEN_SECTION_BATTERY_BG=28

  [[ -z $ALIEN_SECTION_USER_FG ]] && ALIEN_SECTION_USER_FG=232
  [[ -z $ALIEN_SECTION_USER_BG ]] && ALIEN_SECTION_USER_BG=34

  [[ -z $ALIEN_SECTION_PATH_FG ]] && ALIEN_SECTION_PATH_FG=232
  [[ -z $ALIEN_SECTION_PATH_BG ]] && ALIEN_SECTION_PATH_BG=82

  [[ -z $ALIEN_SECTION_VCS_BRANCH_FG ]] && ALIEN_SECTION_VCS_BRANCH_FG=154
  [[ -z $ALIEN_SECTION_VCS_BRANCH_BG ]] && ALIEN_SECTION_VCS_BRANCH_BG=238
  [[ -z $ALIEN_SECTION_VCS_STATUS_FG ]] && ALIEN_SECTION_VCS_STATUS_FG=255
  [[ -z $ALIEN_SECTION_VCS_STATUS_BG ]] && ALIEN_SECTION_VCS_STATUS_BG=244
  [[ -z $ALIEN_SECTION_VCS_DIRTY_FG ]] && ALIEN_SECTION_VCS_DIRTY_FG=16
  [[ -z $ALIEN_SECTION_VCS_DIRTY_BG ]] && ALIEN_SECTION_VCS_DIRTY_BG=253

  [[ -z $ALIEN_SECTION_SSH_FG ]] && ALIEN_SECTION_SSH_FG=245

  [[ -z $ALIEN_SECTION_VENV_FG ]] && ALIEN_SECTION_VENV_FG=245

  [[ -z $PLIB_GIT_TRACKED_COLOR ]] && PLIB_GIT_TRACKED_COLOR=65
  [[ -z $PLIB_GIT_UNTRACKED_COLOR ]] && PLIB_GIT_UNTRACKED_COLOR=236
}
